version: '3.8'

services:
  main-app:
    build:
      context: ./main-app
    ports:
      - "5000:5000"
    depends_on:
      - events
      - hotels

  events:
    build:
      context: ./services/events
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=pariwisata
    depends_on:
      - mysql

  hotels:
    build:
      context: ./services/hotels
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=pariwisata
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pariwisata
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
